env:
  browser: true
extends: 'eslint:recommended'
rules:
  accessor-pairs: 2
  array-bracket-spacing:
    - error
    - never
  array-callback-return: 'off'
  arrow-body-style: 2
  arrow-parens: 2
  arrow-spacing: 2
  block-scoped-var: 2
  block-spacing: 2
  brace-style:
    - error
    - 1tbs
  callback-return: 2
  camelcase: 2
  comma-spacing:
    - error
    - after: true
      before: false
  comma-style:
    - error
    - last
  complexity: 'off'
  computed-property-spacing:
    - error
    - never
  consistent-return: 2
  consistent-this: 'off'
  curly: 2
  default-case: 2
  dot-location:
    - error
    - property
  dot-notation: 2
  eol-last: 2
  eqeqeq: 2
  func-names: 'off'
  func-style:
    - error
    - expression
  generator-star-spacing: 2
  global-require: 2
  guard-for-in: 2
  handle-callback-err: 2
  id-blacklist: 2
  id-length: 'off'
  id-match: 2
  indent: 2
  init-declarations: 'off'
  jsx-quotes: 2
  key-spacing: 2
  keyword-spacing:
    - error
    - after: true
      before: true
  linebreak-style:
    - error
    - unix
  lines-around-comment: 2
  max-depth: 2
  max-len: ["warn", 90]
  max-nested-callbacks: 2
  max-params: 'off'
  max-statements: 'off'
  max-statements-per-line: 2
  new-cap: 2
  new-parens: 2
  newline-after-var: 'off'
  newline-before-return: 'off'
  newline-per-chained-call: 2
  no-alert: 2
  no-array-constructor: 2
  no-bitwise: 2
  no-caller: 2
  no-catch-shadow: 2
  no-confusing-arrow: 2
  no-continue: 2
  no-div-regex: 2
  no-duplicate-imports: 2
  no-else-return: 'off'
  no-empty-function: 'off'
  no-eq-null: 2
  no-eval: 2
  no-extend-native: 2
  no-extra-bind: 2
  no-extra-label: 2
  no-extra-parens: 'off'
  no-floating-decimal: 2
  no-implicit-coercion: 2
  no-implicit-globals: 2
  no-implied-eval: 2
  no-inline-comments: 'off'
  no-inner-declarations:
    - error
    - functions
  no-invalid-this: 'off'
  no-iterator: 2
  no-label-var: 2
  no-labels: 2
  no-lone-blocks: 2
  no-lonely-if: 2
  no-loop-func: 2
  no-magic-numbers: 'off'
  no-mixed-requires: 2
  no-multi-spaces: 2
  no-multi-str: 2
  no-multiple-empty-lines: 2
  no-native-reassign: 2
  no-negated-condition: 'off'
  no-nested-ternary: 0
  no-new: 2
  no-new-func: 2
  no-new-object: 2
  no-new-require: 2
  no-new-wrappers: 2
  no-octal-escape: 2
  no-param-reassign: 'off'
  no-path-concat: 2
  no-plusplus: 'off'
  no-process-env: 2
  no-process-exit: 2
  no-proto: 2
  no-restricted-globals: 2
  no-restricted-imports: 2
  no-restricted-modules: 2
  no-restricted-syntax: 2
  no-return-assign: 2
  no-script-url: 2
  no-self-compare: 2
  no-sequences: 2
  no-shadow: 'off'
  no-shadow-restricted-names: 2
  no-spaced-func: 2
  no-sync: 2
  no-ternary: 'off'
  no-throw-literal: 2
  no-trailing-spaces: 2
  no-undef-init: 2
  no-undefined: 'off'
  no-underscore-dangle: 'off'
  no-unmodified-loop-condition: 2
  no-unneeded-ternary: 2
  no-unused-expressions: 2
  no-unused-vars: 1
  no-use-before-define: 2
  no-useless-call: 2
  no-useless-concat: 2
  no-useless-constructor: 2
  no-useless-escape: 2
  no-var: 'off'
  no-void: 2
  no-warning-comments: 'off'
  no-whitespace-before-property: 2
  no-with: 2
  object-curly-spacing:
    - error
    - always
  object-shorthand: 'off'
  one-var: 'off'
  one-var-declaration-per-line: 2
  operator-assignment:
    - error
    - always
  operator-linebreak:
    - error
    - after
  padded-blocks: 'off'
  prefer-arrow-callback: 'off'
  prefer-const: 2
  prefer-reflect: 2
  prefer-rest-params: 0
  prefer-spread: 2
  prefer-template: 'off'
  quote-props: 'off'
  quotes:
    - error
    - single
  radix: 2
  require-jsdoc: 2
  require-yield: 2
  semi: 2
  semi-spacing:
    - error
    - after: true
      before: false
  sort-imports: 2
  sort-vars: 2
  space-before-blocks: 2
  space-before-function-paren: 2
  space-in-parens:
    - error
    - never
  space-infix-ops: 2
  space-unary-ops: 2
  spaced-comment:
    - error
    - always
  strict:
    - error
    - global
  template-curly-spacing: 2
  valid-jsdoc: 2
  vars-on-top: 'off'
  wrap-iife: 2
  wrap-regex: 2
  yield-star-spacing: 2
  yoda:
    - error
    - never
globals:
  Ionic: false,
  cordova: false,
  StatusBar: false,
  $: false,
  angular: false,
  browser: false,
  repeater: false,
  element: false,
  inject: false,
  afterEach: false,
  beforeEach: false,
  confirm: false,
  context: false,
  describe: false,
  expect: false,
  it: false,
  jasmine: true,
  JSHINT: false,
  module: false,
  mostRecentAjaxRequest: false,
  qq: false,
  runs: false,
  spyOn: false,
  spyOnEvent: false,
  waitsFor: false,
  ionic: false,
  head: false,
  xit: false,
  xdescribe: false,
  by: false
